version: '3.1'

services:

    wordpress:
        build:
            context: .
        depends_on:
            - db
        volumes: # Map from a loacal directory
            - ./plugins:/var/www/html/wp-content/plugins
        restart: always
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_NAME: wordpress
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress

    db:
        # mysql/mysql-server is less in size than mysql
        # mysql-server:8.0 is not working by default
        image: mysql/mysql-server:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
